#!/bin/sh
. "$(dirname "$0")/_/husky.sh"


echo ' Styling, testing and building your project before commiting'

#check prettier
npm run check-format ||
(

  echo 'Prettier check failed, Run npm run format , add changes and try commit again';
  false;
)

#Check Eslint
npm run check-lint || 
(
 echo "Eslint  check failed, make the required changed listed above, add changes and
  try to  commit again";
  false;
)

#Check tsconfig
npm run check-types ||
(

 echo "failed type check. make the changes require above, add changes and try to commit again";
 false;

)

npm run build || 
(

  echo "your  build  failed, view the errors above";
  false;
)

echo "success committing"